# Generated by Django 3.0.2 on 2020-01-29 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=256, verbose_name='元の単語')),
                ('target', models.CharField(blank=True, max_length=256, verbose_name='翻訳単語')),
                ('source_lang', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('it', 'Italian')], max_length=256, verbose_name='元言語')),
                ('target_lang', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('it', 'Italian')], max_length=256, verbose_name='目標言語')),
                ('model', models.CharField(choices=[('muse_sup', 'MUSE教師あり'), ('muse_unsup', 'MUSE教師なし'), ('joint_align', 'Joint_align')], max_length=256, verbose_name='モデル')),
            ],
        ),
    ]
