# Generated by Django 3.0.2 on 2020-02-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crosslingual', '0003_auto_20200129_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translate',
            name='source_lang',
        ),
        migrations.RemoveField(
            model_name='translate',
            name='target_lang',
        ),
        migrations.AddField(
            model_name='translate',
            name='src_tgt_lang',
            field=models.CharField(choices=[('en-es', '英語→スペイン語'), ('es-en', 'スペイン語→英語'), ('en-ja', '英語→日本語'), ('ja-en', '日本語→英語'), ('it-es', 'イタリア語→スペイン語'), ('es-it', 'スペイン語→イタリア語')], default='en-es', max_length=256, verbose_name='言語対'),
        ),
    ]
