# Generated by Django 3.0.2 on 2020-02-14 00:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crosslingual', '0004_auto_20200202_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='translate',
            name='target_joint',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), max_length=160, null=True, size=5),
        ),
        migrations.AlterField(
            model_name='translate',
            name='src_tgt_lang',
            field=models.CharField(choices=[('en-es', '英語→スペイン語'), ('es-en', 'スペイン語→英語'), ('en-ja', '英語→日本語'), ('ja-en', '日本語→英語'), ('en-it', '英語→イタリア語'), ('it-en', 'イタリア語→英語'), ('it-es', 'イタリア語→スペイン語'), ('es-it', 'スペイン語→イタリア語')], default='en-es', max_length=256, verbose_name='言語対'),
        ),
    ]
