# Generated by Django 3.0.2 on 2020-09-10 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crosslingual', '0006_frequenttable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translate',
            name='src_tgt_lang',
        ),
        migrations.AddField(
            model_name='translate',
            name='src_lang',
            field=models.CharField(choices=[('en', '英語'), ('es', 'スペイン語'), ('fr', 'フランス語'), ('it', 'イタリア語')], default='en', max_length=256, verbose_name='入力言語'),
        ),
        migrations.AddField(
            model_name='translate',
            name='tgt_lang',
            field=models.CharField(choices=[('en', '英語'), ('es', 'スペイン語'), ('fr', 'フランス語'), ('it', 'イタリア語')], default='es', max_length=256, verbose_name='出力言語'),
        ),
    ]
