# Generated by Django 3.0.2 on 2020-09-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crosslingual', '0007_auto_20200910_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequenttable',
            name='src_lang',
            field=models.CharField(choices=[('en', '英語'), ('es', 'スペイン語'), ('es', 'フランス語'), ('it', 'イタリア語'), ('ja', '日本語'), ('pt', 'ポルトガル語'), ('la', 'ラテン語'), ('eo', 'エスペラント語'), ('nl', 'オランダ語'), ('ru', 'ロシア語'), ('th', 'タイ語'), ('ko', '韓国語'), ('zh', '中国語')], max_length=256, verbose_name='入力言語'),
        ),
        migrations.AlterField(
            model_name='frequenttable',
            name='tgt_lang',
            field=models.CharField(choices=[('en', '英語'), ('es', 'スペイン語'), ('es', 'フランス語'), ('it', 'イタリア語'), ('ja', '日本語'), ('pt', 'ポルトガル語'), ('la', 'ラテン語'), ('eo', 'エスペラント語'), ('nl', 'オランダ語'), ('ru', 'ロシア語'), ('th', 'タイ語'), ('ko', '韓国語'), ('zh', '中国語')], max_length=256, verbose_name='出力言語'),
        ),
        migrations.AlterField(
            model_name='translate',
            name='src_lang',
            field=models.CharField(choices=[('en', '英語'), ('es', 'スペイン語'), ('fr', 'フランス語'), ('it', 'イタリア語')], max_length=256, verbose_name='入力言語'),
        ),
        migrations.AlterField(
            model_name='translate',
            name='tgt_lang',
            field=models.CharField(choices=[('en', '英語'), ('es', 'スペイン語'), ('fr', 'フランス語'), ('it', 'イタリア語')], max_length=256, verbose_name='出力言語'),
        ),
    ]
