# Generated by Django 3.0.2 on 2020-09-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crosslingual', '0008_auto_20200924_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translate',
            name='src_lang',
            field=models.CharField(choices=[('en', '英語'), ('es', 'スペイン語'), ('fr', 'フランス語'), ('it', 'イタリア語'), ('ja', '日本語')], max_length=256, verbose_name='入力言語'),
        ),
        migrations.AlterField(
            model_name='translate',
            name='tgt_lang',
            field=models.CharField(choices=[('en', '英語'), ('es', 'スペイン語'), ('fr', 'フランス語'), ('it', 'イタリア語'), ('ja', '日本語')], max_length=256, verbose_name='出力言語'),
        ),
    ]
