# Generated by Django 3.0.2 on 2020-04-08 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0002_auto_20200408_0647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='order',
        ),
    ]
