# Generated by Django 3.0.2 on 2020-04-10 08:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0003_remove_paper_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='expired',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='read_date',
        ),
        migrations.AddField(
            model_name='paper',
            name='edit_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='最終編集日'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='field',
            field=models.CharField(choices=[('RVSML', 'RVSML'), ('文類似性尺度', '文類似性尺度'), ('Cross lingual', 'Cross lingual')], default='研究', max_length=32, verbose_name='分野'),
        ),
    ]
